/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VirtualScrollIndexRouteImport } from './routes/virtual-scroll/index'
import { Route as PointerTrackerIndexRouteImport } from './routes/pointer-tracker/index'
import { Route as PaginationIndexRouteImport } from './routes/pagination/index'
import { Route as OtpInputIndexRouteImport } from './routes/otp-input/index'
import { Route as DragAndDropIndexRouteImport } from './routes/drag-and-drop/index'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VirtualScrollIndexRoute = VirtualScrollIndexRouteImport.update({
  id: '/virtual-scroll/',
  path: '/virtual-scroll/',
  getParentRoute: () => rootRouteImport,
} as any)
const PointerTrackerIndexRoute = PointerTrackerIndexRouteImport.update({
  id: '/pointer-tracker/',
  path: '/pointer-tracker/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginationIndexRoute = PaginationIndexRouteImport.update({
  id: '/pagination/',
  path: '/pagination/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpInputIndexRoute = OtpInputIndexRouteImport.update({
  id: '/otp-input/',
  path: '/otp-input/',
  getParentRoute: () => rootRouteImport,
} as any)
const DragAndDropIndexRoute = DragAndDropIndexRouteImport.update({
  id: '/drag-and-drop/',
  path: '/drag-and-drop/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/drag-and-drop/': typeof DragAndDropIndexRoute
  '/otp-input/': typeof OtpInputIndexRoute
  '/pagination/': typeof PaginationIndexRoute
  '/pointer-tracker/': typeof PointerTrackerIndexRoute
  '/virtual-scroll/': typeof VirtualScrollIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/drag-and-drop': typeof DragAndDropIndexRoute
  '/otp-input': typeof OtpInputIndexRoute
  '/pagination': typeof PaginationIndexRoute
  '/pointer-tracker': typeof PointerTrackerIndexRoute
  '/virtual-scroll': typeof VirtualScrollIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/drag-and-drop/': typeof DragAndDropIndexRoute
  '/otp-input/': typeof OtpInputIndexRoute
  '/pagination/': typeof PaginationIndexRoute
  '/pointer-tracker/': typeof PointerTrackerIndexRoute
  '/virtual-scroll/': typeof VirtualScrollIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/directory/'
    | '/drag-and-drop/'
    | '/otp-input/'
    | '/pagination/'
    | '/pointer-tracker/'
    | '/virtual-scroll/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/directory'
    | '/drag-and-drop'
    | '/otp-input'
    | '/pagination'
    | '/pointer-tracker'
    | '/virtual-scroll'
  id:
    | '__root__'
    | '/'
    | '/directory/'
    | '/drag-and-drop/'
    | '/otp-input/'
    | '/pagination/'
    | '/pointer-tracker/'
    | '/virtual-scroll/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  DragAndDropIndexRoute: typeof DragAndDropIndexRoute
  OtpInputIndexRoute: typeof OtpInputIndexRoute
  PaginationIndexRoute: typeof PaginationIndexRoute
  PointerTrackerIndexRoute: typeof PointerTrackerIndexRoute
  VirtualScrollIndexRoute: typeof VirtualScrollIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virtual-scroll/': {
      id: '/virtual-scroll/'
      path: '/virtual-scroll'
      fullPath: '/virtual-scroll/'
      preLoaderRoute: typeof VirtualScrollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pointer-tracker/': {
      id: '/pointer-tracker/'
      path: '/pointer-tracker'
      fullPath: '/pointer-tracker/'
      preLoaderRoute: typeof PointerTrackerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagination/': {
      id: '/pagination/'
      path: '/pagination'
      fullPath: '/pagination/'
      preLoaderRoute: typeof PaginationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-input/': {
      id: '/otp-input/'
      path: '/otp-input'
      fullPath: '/otp-input/'
      preLoaderRoute: typeof OtpInputIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drag-and-drop/': {
      id: '/drag-and-drop/'
      path: '/drag-and-drop'
      fullPath: '/drag-and-drop/'
      preLoaderRoute: typeof DragAndDropIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  DragAndDropIndexRoute: DragAndDropIndexRoute,
  OtpInputIndexRoute: OtpInputIndexRoute,
  PaginationIndexRoute: PaginationIndexRoute,
  PointerTrackerIndexRoute: PointerTrackerIndexRoute,
  VirtualScrollIndexRoute: VirtualScrollIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
